spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
        # 精确的路由要放到上边
        - id: product_route
          uri: http://localhost:20000
          predicates: # 断言
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: http://localhost:8080       #lb://renren-fast
          predicates: # 断言
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}



# 只要是前端项目发送请求,都带上api前缀